// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Prisma 7 : plus de champ `directUrl` dans ce type de config (seulement
// `url` / `shadowDatabaseUrl`). Les commandes CLI (migrate, studio...) ont
// besoin d'une connexion directe (non poolée) pour poser leurs verrous
// d'avisory lock — on leur passe donc DIRECT_URL ici. Le client Prisma de
// l'application (src/lib/prisma.ts), lui, se connecte séparément avec
// DATABASE_URL (poolée via PgBouncer) grâce à l'adaptateur @prisma/adapter-pg.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
